name: payphont
description: A full-featured business assistant app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # state & storage
  hooks_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # ui & charts
  go_router: ^13.0.0
  fl_chart: ^0.63.0
  file_picker: ^6.1.1
  local_auth: ^2.1.6
  url_launcher: ^6.2.5

  # export
  pdf: ^3.10.4
  excel: ^2.1.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
